export type PropertyType = 'Room' | 'Flat' | 'PG' | 'House' | 'Villa' | 'Apartment' | 'Shop' | 'Office' | 'Showroom' | 'Warehouse' | 'Agriculture Land' | 'Plot' | 'Farm House' | 'Hostel';
export type ListingType = 'Rent' | 'Sale' | 'Lease';
export type PropertyStatus = 'live' | 'pending' | 'rejected' | 'draft';

export interface Property {
  id: string;
  title: string;
  description: string;
  price: number;
  priceType: 'monthly' | 'fixed';
  propertyType: PropertyType;
  listingType: ListingType;
  status: PropertyStatus;
  verified: boolean;
  address: string;
  city: string;
  locality: string;
  photos: string[];
  ownerName: string;
  ownerMobile: string;
  ownerMobileHidden: boolean;
  amenities: string[];
  bedrooms?: number;
  bathrooms?: number;
  floor?: string;
  totalFloors?: number;
  propertyAge?: string;
  furnished?: 'Furnished' | 'Semi-Furnished' | 'Unfurnished';
  preferredTenant?: 'Family' | 'Bachelor' | 'Anyone';
  builtUpArea?: number;
  plotArea?: number;
  roadWidth?: string;
  availableFrom?: string;
  createdAt: string;
  updatedAt: string;
  reportedCount: number;
  lat?: number;
  lng?: number;
  views: number;
  plan?: PlanType;
}

export type PlanType = 'free' | 'boosted' | 'premium' | 'superPremium' | 'premiumOwner';

export const propertyTypeIcons: Record<PropertyType, string> = {
  'Room': 'Bed',
  'Flat': 'Building',
  'PG': 'BedDouble',
  'House': 'Home',
  'Villa': 'Castle',
  'Apartment': 'Building2',
  'Shop': 'Store',
  'Office': 'Briefcase',
  'Showroom': 'Building',
  'Warehouse': 'Warehouse',
  'Agriculture Land': 'Wheat',
  'Plot': 'Map',
  'Farm House': 'Trees',
  'Hostel': 'Users',
};

export interface ServiceItem {
  id: string;
  nameKey: string;
  icon: string;
  route: string;
}

export const servicesList: ServiceItem[] = [
  { id: 'home-cleaning', nameKey: 'serviceHomeCleaning', icon: 'Sparkles', route: '/services/home-cleaning' },
  { id: 'painter', nameKey: 'servicePainter', icon: 'PaintBucket', route: '/services/painter' },
  { id: 'electrician', nameKey: 'serviceElectrician', icon: 'Zap', route: '/services/electrician' },
  { id: 'plumber', nameKey: 'servicePlumber', icon: 'Droplets', route: '/services/plumber' },
  { id: 'packers-movers', nameKey: 'servicePackersMovers', icon: 'Truck', route: '/services/packers-movers' },
  { id: 'solar', nameKey: 'serviceSolar', icon: 'Sun', route: '/services/solar' },
  { id: 'home-loan', nameKey: 'serviceHomeLoan', icon: 'Banknote', route: '/services/home-loan' },
  { id: 'interior', nameKey: 'serviceInterior', icon: 'Palette', route: '/services/interior' },
  { id: 'cctv', nameKey: 'serviceCCTV', icon: 'Camera', route: '/services/cctv' },
  { id: 'construction', nameKey: 'serviceConstruction', icon: 'BrickWall', route: '/services/construction' },
  { id: 'carpenter', nameKey: 'serviceCarpenter', icon: 'Hammer', route: '/services/carpenter' },
  { id: 'water-tank', nameKey: 'serviceWaterTank', icon: 'Container', route: '/services/water-tank' },
];

export const amenitiesByType: Record<PropertyType, string[]> = {
  'Room': ['Water Supply', 'Electricity', 'Security', 'Bachelor Allowed', 'Family Allowed', 'Separate Entry', 'Pet Allowed', 'WiFi', 'AC', 'Geyser', 'Parking'],
  'Flat': ['Parking', 'Water Supply', 'Electricity', 'Security', 'Lift', 'Balcony', 'Kitchen', 'Power Backup', 'WiFi', 'AC', 'Geyser', 'Family Allowed', 'Bachelor Allowed', 'Pet Allowed'],
  'PG': ['WiFi', 'Water Supply', 'Electricity', 'Security', 'Food', 'AC', 'Power Backup', 'Lift', 'Kitchen', 'Laundry', 'Bachelor Allowed', 'Family Allowed', 'Hot Water', 'TV'],
  'House': ['Parking', 'Water Supply', 'Electricity', 'Garden', 'Security', 'Family Allowed', 'Pet Allowed', 'Power Backup', 'Separate Entry', 'Balcony', 'Kitchen', 'Store Room'],
  'Villa': ['Parking', 'Water Supply', 'Electricity', 'Garden', 'Security', 'Swimming Pool', 'Power Backup', 'Family Allowed', 'Pet Allowed', 'Lift', 'Servant Quarter', 'AC', 'Gym Access'],
  'Apartment': ['Parking', 'Water Supply', 'Electricity', 'Security', 'Lift', 'Balcony', 'Kitchen', 'Power Backup', 'WiFi', 'AC', 'Geyser', 'Family Allowed', 'Bachelor Allowed', 'Gym', 'Club House'],
  'Shop': ['Electricity', 'Water Supply', 'Security', 'Power Backup', 'Parking', 'Fire Safety', 'CCTV', 'Lift'],
  'Office': ['Parking', 'Electricity', 'Water Supply', 'Security', 'Power Backup', 'Lift', 'WiFi', 'CCTV', 'Fire Safety', 'Conference Room'],
  'Showroom': ['Parking', 'Electricity', 'Water Supply', 'Security', 'Power Backup', 'CCTV', 'Fire Safety', 'Air Conditioning'],
  'Warehouse': ['Parking', 'Electricity', 'Water Supply', 'Security', 'CCTV', 'Fire Safety', 'Loading Dock', '24x7 Access'],
  'Agriculture Land': ['Water Supply', 'Electricity', 'Road Access', 'Irrigation', 'Fencing', 'Borewell'],
  'Plot': ['Water Supply', 'Electricity', 'Road Access', 'Gated Community', 'Street Lighting', 'Sewage'],
  'Farm House': ['Parking', 'Water Supply', 'Electricity', 'Garden', 'Security', 'Pet Allowed', 'Farm Land', 'Borewell', 'Storage'],
  'Hostel': ['WiFi', 'Water Supply', 'Electricity', 'Security', 'Food', 'AC', 'Power Backup', 'Laundry', 'Hot Water', 'TV', 'Study Room', 'Bachelor Allowed'],
};

export const amenitiesList = [
  'Parking',
  'Water Supply',
  'Electricity',
  'Security',
  'Lift',
  'Balcony',
  'Kitchen',
  'Separate Entry',
  'Pet Allowed',
  'Family Allowed',
  'Bachelor Allowed',
  'Power Backup',
  'WiFi',
  'AC',
  'Geyser',
  'Garden',
  'Swimming Pool',
  'Servant Quarter',
  'Gym',
  'Club House',
  'Laundry',
  'Hot Water',
  'TV',
  'Store Room',
  'Gym Access',
  'Fire Safety',
  'CCTV',
  'Conference Room',
  'Air Conditioning',
  'Loading Dock',
  '24x7 Access',
  'Irrigation',
  'Fencing',
  'Borewell',
  'Gated Community',
  'Street Lighting',
  'Sewage',
  'Farm Land',
  'Study Room',
  'Food',
];

export const cities = ['Lucknow', 'Delhi', 'Mumbai', 'Bangalore', 'Jaipur'];

export const propertyTypes: PropertyType[] = ['Room', 'Flat', 'PG', 'House', 'Villa', 'Apartment', 'Shop', 'Office', 'Showroom', 'Warehouse', 'Agriculture Land', 'Plot', 'Farm House', 'Hostel'];

// Only these 8 types shown on Home screen with icons
export const homePropertyTypes: { type: PropertyType; icon: string }[] = [
  { type: 'Room', icon: 'Bed' },
  { type: 'Flat', icon: 'Building' },
  { type: 'House', icon: 'Home' },
  { type: 'PG', icon: 'BedDouble' },
  { type: 'Plot', icon: 'Map' },
  { type: 'Shop', icon: 'Store' },
  { type: 'Office', icon: 'Briefcase' },
  { type: 'Warehouse', icon: 'Warehouse' },
];

export const listingTypes: ListingType[] = ['Rent', 'Sale', 'Lease'];

export const reportReasons = [
  'Fake property',
  'Wrong location',
  'Already rented/sold',
  'Wrong price',
  'Broker listing',
  'Fraud/suspicious',
  'Other',
];

export const properties: Property[] = [
  {
    id: 'prop_001',
    title: 'Spacious 2BHK Flat with Balcony View',
    description: 'Beautiful 2BHK flat in a prime location with excellent connectivity. Features a large balcony with city view, modular kitchen, and ample natural light. Ideal for families.',
    price: 18000,
    priceType: 'monthly',
    propertyType: 'Flat',
    listingType: 'Rent',
    status: 'live',
    verified: true,
    address: 'B-402, Sunshine Apartments, Vrindavan Yojna, Lucknow',
    city: 'Lucknow',
    locality: 'Vrindavan Yojna',
    photos: ['/prop-sample-1.jpg'],
    ownerName: 'Amit Sharma',
    ownerMobile: '9876543210',
    ownerMobileHidden: true,
    amenities: ['Parking', 'Water Supply', 'Electricity', 'Lift', 'Balcony', 'Kitchen', 'Security', 'Family Allowed'],
    bedrooms: 2,
    bathrooms: 2,
    floor: '4',
    totalFloors: 8,
    propertyAge: '3-5 years',
    furnished: 'Semi-Furnished',
    preferredTenant: 'Family',
    builtUpArea: 1050,
    createdAt: '2024-12-15T10:30:00Z',
    updatedAt: '2024-12-15T10:30:00Z',
    reportedCount: 0,
    views: 342,
  },
  {
    id: 'prop_002',
    title: 'Cozy Single Room with Attached Bath',
    description: 'Well-maintained single room with attached bathroom. Perfect for working professionals or students. Close to market and transport.',
    price: 5500,
    priceType: 'monthly',
    propertyType: 'Room',
    listingType: 'Rent',
    status: 'live',
    verified: true,
    address: '12, Ramesh Nagar, Near Metro Station, Delhi',
    city: 'Delhi',
    locality: 'Ramesh Nagar',
    photos: ['/prop-sample-2.jpg'],
    ownerName: 'Suresh Kumar',
    ownerMobile: '8765432109',
    ownerMobileHidden: true,
    amenities: ['Water Supply', 'Electricity', 'Security', 'Bachelor Allowed', 'Separate Entry'],
    bedrooms: 1,
    bathrooms: 1,
    floor: '2',
    totalFloors: 3,
    propertyAge: '5-10 years',
    furnished: 'Furnished',
    preferredTenant: 'Bachelor',
    builtUpArea: 250,
    createdAt: '2025-01-05T08:15:00Z',
    updatedAt: '2025-01-05T08:15:00Z',
    reportedCount: 0,
    views: 189,
  },
  {
    id: 'prop_003',
    title: 'Independent House with Garden',
    description: 'Beautiful independent house with small garden and parking space. Located in a peaceful residential colony. Perfect for families seeking privacy.',
    price: 4500000,
    priceType: 'fixed',
    propertyType: 'House',
    listingType: 'Sale',
    status: 'live',
    verified: true,
    address: '45, Shanti Niketan Colony, Malviya Nagar, Jaipur',
    city: 'Jaipur',
    locality: 'Malviya Nagar',
    photos: ['/prop-sample-3.jpg'],
    ownerName: 'Rajesh Gupta',
    ownerMobile: '7654321098',
    ownerMobileHidden: true,
    amenities: ['Parking', 'Water Supply', 'Electricity', 'Garden', 'Security', 'Family Allowed', 'Pet Allowed'],
    bedrooms: 3,
    bathrooms: 2,
    propertyAge: '5-10 years',
    furnished: 'Unfurnished',
    plotArea: 1800,
    builtUpArea: 1400,
    createdAt: '2025-01-10T14:00:00Z',
    updatedAt: '2025-01-10T14:00:00Z',
    reportedCount: 0,
    views: 567,
  },
  {
    id: 'prop_004',
    title: 'Prime Commercial Shop on Main Road',
    description: 'Ground floor commercial shop on busy main road with excellent visibility. High footfall area suitable for any business.',
    price: 35000,
    priceType: 'monthly',
    propertyType: 'Shop',
    listingType: 'Rent',
    status: 'live',
    verified: false,
    address: 'Shop 8, Lajpat Nagar Market, Mumbai',
    city: 'Mumbai',
    locality: 'Lajpat Nagar',
    photos: ['/prop-sample-4.jpg'],
    ownerName: 'Priya Mehta',
    ownerMobile: '6543210987',
    ownerMobileHidden: true,
    amenities: ['Electricity', 'Water Supply', 'Security'],
    floor: 'Ground',
    propertyAge: '1-2 years',
    builtUpArea: 400,
    roadWidth: '40 ft',
    createdAt: '2025-01-12T11:20:00Z',
    updatedAt: '2025-01-12T11:20:00Z',
    reportedCount: 0,
    views: 234,
  },
  {
    id: 'prop_005',
    title: 'Agricultural Land with Clear Title',
    description: 'Fertile agricultural land with clear boundaries and proper irrigation facility. Road access available. Ideal for farming or investment.',
    price: 2500000,
    priceType: 'fixed',
    propertyType: 'Agriculture Land',
    listingType: 'Sale',
    status: 'live',
    verified: true,
    address: 'Village Kheda, Near Highway, Lucknow District',
    city: 'Lucknow',
    locality: 'Kheda Village',
    photos: ['/prop-sample-5.jpg'],
    ownerName: 'Ram Prasad',
    ownerMobile: '5432109876',
    ownerMobileHidden: true,
    amenities: ['Water Supply', 'Electricity', 'Road Access'],
    plotArea: 10800,
    roadWidth: '20 ft',
    createdAt: '2025-01-15T09:00:00Z',
    updatedAt: '2025-01-15T09:00:00Z',
    reportedCount: 0,
    views: 445,
  },
  {
    id: 'prop_006',
    title: 'PG for Students near University',
    description: 'Comfortable PG accommodation with food facility. Shared rooms with study tables, WiFi, and housekeeping. Walking distance from university.',
    price: 8000,
    priceType: 'monthly',
    propertyType: 'PG',
    listingType: 'Rent',
    status: 'live',
    verified: true,
    address: '15, University Road, Jalandhar, Near PU Campus',
    city: 'Delhi',
    locality: 'University Road',
    photos: ['/prop-sample-6.jpg'],
    ownerName: 'Kiran Devi',
    ownerMobile: '4321098765',
    ownerMobileHidden: true,
    amenities: ['WiFi', 'Water Supply', 'Electricity', 'Security', 'Food', 'AC', 'Power Backup', 'Bachelor Allowed'],
    bedrooms: 2,
    bathrooms: 1,
    floor: '1',
    totalFloors: 3,
    propertyAge: '2-3 years',
    furnished: 'Furnished',
    preferredTenant: 'Bachelor',
    builtUpArea: 600,
    createdAt: '2025-01-18T07:45:00Z',
    updatedAt: '2025-01-18T07:45:00Z',
    reportedCount: 0,
    views: 278,
  },
  {
    id: 'prop_007',
    title: '3BHK Luxury Flat in Gated Society',
    description: 'Premium 3BHK flat in a gated community with clubhouse, swimming pool, and gym. Corner unit with panoramic views.',
    price: 32000,
    priceType: 'monthly',
    propertyType: 'Flat',
    listingType: 'Rent',
    status: 'live',
    verified: true,
    address: 'Tower C, Green Valley Residency, Whitefield, Bangalore',
    city: 'Bangalore',
    locality: 'Whitefield',
    photos: ['/prop-sample-1.jpg'],
    ownerName: 'Vikram Singh',
    ownerMobile: '3210987654',
    ownerMobileHidden: true,
    amenities: ['Parking', 'Water Supply', 'Electricity', 'Lift', 'Balcony', 'Kitchen', 'Security', 'Power Backup', 'Family Allowed', 'AC'],
    bedrooms: 3,
    bathrooms: 3,
    floor: '7',
    totalFloors: 15,
    propertyAge: '1-2 years',
    furnished: 'Furnished',
    preferredTenant: 'Family',
    builtUpArea: 1650,
    createdAt: '2025-02-01T16:30:00Z',
    updatedAt: '2025-02-01T16:30:00Z',
    reportedCount: 0,
    views: 891,
  },
  {
    id: 'prop_008',
    title: '1RK Studio Apartment for Rent',
    description: 'Compact studio apartment perfect for single professionals. Fully furnished with kitchenette and modern bathroom.',
    price: 9000,
    priceType: 'monthly',
    propertyType: 'Flat',
    listingType: 'Rent',
    status: 'live',
    verified: false,
    address: 'Flat 302, Sai Residency, Andheri West, Mumbai',
    city: 'Mumbai',
    locality: 'Andheri West',
    photos: ['/prop-sample-2.jpg'],
    ownerName: 'Neha Patel',
    ownerMobile: '2109876543',
    ownerMobileHidden: true,
    amenities: ['Water Supply', 'Electricity', 'Security', 'Lift', 'Bachelor Allowed'],
    bedrooms: 1,
    bathrooms: 1,
    floor: '3',
    totalFloors: 5,
    propertyAge: '3-5 years',
    furnished: 'Furnished',
    preferredTenant: 'Anyone',
    builtUpArea: 350,
    createdAt: '2025-02-05T12:00:00Z',
    updatedAt: '2025-02-05T12:00:00Z',
    reportedCount: 1,
    views: 156,
  },
  {
    id: 'prop_009',
    title: 'Commercial Office Space in Tech Park',
    description: 'Modern office space in IT tech park with cabin, conference room, and open workspace. Ready to move in.',
    price: 75000,
    priceType: 'monthly',
    propertyType: 'Shop',
    listingType: 'Rent',
    status: 'pending',
    verified: false,
    address: 'Block B, Tech Park Phase 2, Electronic City, Bangalore',
    city: 'Bangalore',
    locality: 'Electronic City',
    photos: ['/prop-sample-4.jpg'],
    ownerName: 'Infospace Realtors',
    ownerMobile: '1098765432',
    ownerMobileHidden: true,
    amenities: ['Parking', 'Water Supply', 'Electricity', 'Lift', 'Security', 'Power Backup', 'WiFi'],
    floor: '3',
    totalFloors: 12,
    propertyAge: 'New',
    furnished: 'Semi-Furnished',
    builtUpArea: 2200,
    createdAt: '2025-02-10T09:30:00Z',
    updatedAt: '2025-02-10T09:30:00Z',
    reportedCount: 0,
    views: 67,
  },
  {
    id: 'prop_010',
    title: 'Double Storey Villa for Sale',
    description: 'Spacious double storey villa with 4 bedrooms, garden, and servant quarters. Gated community with 24/7 security.',
    price: 18500000,
    priceType: 'fixed',
    propertyType: 'House',
    listingType: 'Sale',
    status: 'live',
    verified: true,
    address: '42, Palm Meadows, Jubilee Hills, Hyderabad Road, Bangalore',
    city: 'Bangalore',
    locality: 'Jubilee Hills',
    photos: ['/prop-sample-3.jpg'],
    ownerName: 'Dr. Arun Reddy',
    ownerMobile: '9988776655',
    ownerMobileHidden: true,
    amenities: ['Parking', 'Water Supply', 'Electricity', 'Lift', 'Garden', 'Security', 'Power Backup', 'Family Allowed', 'Pet Allowed', 'AC'],
    bedrooms: 4,
    bathrooms: 4,
    propertyAge: '1-2 years',
    furnished: 'Semi-Furnished',
    plotArea: 3600,
    builtUpArea: 3200,
    createdAt: '2025-02-12T15:00:00Z',
    updatedAt: '2025-02-12T15:00:00Z',
    reportedCount: 0,
    views: 723,
  },
  {
    id: 'prop_011',
    title: 'Budget Room in Sharing for Students',
    description: 'Affordable sharing room for students near coaching centers. Two students per room. Homely food available.',
    price: 4000,
    priceType: 'monthly',
    propertyType: 'PG',
    listingType: 'Rent',
    status: 'draft',
    verified: false,
    address: '8, Kota Line, near Allen Career Institute, Jaipur',
    city: 'Jaipur',
    locality: 'Kota Line',
    photos: ['/prop-sample-6.jpg'],
    ownerName: 'Mohan Lal',
    ownerMobile: '8877665544',
    ownerMobileHidden: true,
    amenities: ['Water Supply', 'Electricity', 'WiFi', 'Food', 'Bachelor Allowed'],
    bedrooms: 1,
    bathrooms: 1,
    floor: '1',
    totalFloors: 2,
    propertyAge: '10+ years',
    furnished: 'Furnished',
    preferredTenant: 'Bachelor',
    builtUpArea: 180,
    createdAt: '2025-02-15T10:00:00Z',
    updatedAt: '2025-02-15T10:00:00Z',
    reportedCount: 0,
    views: 45,
  },
  {
    id: 'prop_012',
    title: 'Residential Plot in Developing Area',
    description: 'Corner plot in fast-developing area near proposed metro station. Great investment opportunity with high appreciation potential.',
    price: 5200000,
    priceType: 'fixed',
    propertyType: 'Plot',
    listingType: 'Sale',
    status: 'live',
    verified: true,
    address: 'Plot 88, Sector 45, Noida Extension, Delhi NCR',
    city: 'Delhi',
    locality: 'Noida Extension',
    photos: ['/prop-sample-5.jpg'],
    ownerName: 'Sanjay Verma',
    ownerMobile: '7766554433',
    ownerMobileHidden: true,
    amenities: ['Water Supply', 'Electricity', 'Road Access'],
    plotArea: 2000,
    roadWidth: '30 ft',
    createdAt: '2025-02-18T11:30:00Z',
    updatedAt: '2025-02-18T11:30:00Z',
    reportedCount: 0,
    views: 612,
  },
  {
    id: 'prop_013',
    title: '1BHK Flat for Couples',
    description: 'Cozy 1BHK flat in a quiet neighborhood. Perfect for newly married couples. Close to parks and shopping areas.',
    price: 12000,
    priceType: 'monthly',
    propertyType: 'Flat',
    listingType: 'Rent',
    status: 'rejected',
    verified: false,
    address: 'A-15, Rose Garden Apartments, Gomti Nagar, Lucknow',
    city: 'Lucknow',
    locality: 'Gomti Nagar',
    photos: ['/prop-sample-1.jpg'],
    ownerName: 'Fatima Begum',
    ownerMobile: '6655443322',
    ownerMobileHidden: true,
    amenities: ['Parking', 'Water Supply', 'Electricity', 'Lift', 'Kitchen', 'Family Allowed'],
    bedrooms: 1,
    bathrooms: 1,
    floor: '2',
    totalFloors: 6,
    propertyAge: '5-10 years',
    furnished: 'Semi-Furnished',
    preferredTenant: 'Family',
    builtUpArea: 600,
    createdAt: '2025-02-20T08:00:00Z',
    updatedAt: '2025-02-20T08:00:00Z',
    reportedCount: 2,
    views: 98,
  },
  {
    id: 'prop_014',
    title: 'Shop for Sale in Mall',
    description: 'Ground floor shop in popular shopping mall with high footfall. Suitable for retail, food court, or showroom.',
    price: 8500000,
    priceType: 'fixed',
    propertyType: 'Shop',
    listingType: 'Sale',
    status: 'live',
    verified: true,
    address: 'Shop 12, Ground Floor, City Center Mall, C Scheme, Jaipur',
    city: 'Jaipur',
    locality: 'C Scheme',
    photos: ['/prop-sample-4.jpg'],
    ownerName: 'Rahul Jain',
    ownerMobile: '5544332211',
    ownerMobileHidden: true,
    amenities: ['Parking', 'Electricity', 'Water Supply', 'Security', 'Power Backup'],
    floor: 'Ground',
    propertyAge: '3-5 years',
    builtUpArea: 550,
    createdAt: '2025-02-22T13:45:00Z',
    updatedAt: '2025-02-22T13:45:00Z',
    reportedCount: 0,
    views: 389,
  },
  {
    id: 'prop_015',
    title: 'Premium PG for Working Women',
    description: 'Safe and secure PG exclusively for working women. Single and double sharing options. Homely meals and housekeeping included.',
    price: 12000,
    priceType: 'monthly',
    propertyType: 'PG',
    listingType: 'Rent',
    status: 'live',
    verified: true,
    address: '28, Saket Complex, Koramangala, Bangalore',
    city: 'Bangalore',
    locality: 'Koramangala',
    photos: ['/prop-sample-6.jpg'],
    ownerName: 'Lakshmi Iyer',
    ownerMobile: '4433221100',
    ownerMobileHidden: true,
    amenities: ['WiFi', 'Water Supply', 'Electricity', 'Security', 'Food', 'AC', 'Power Backup', 'Lift', 'Kitchen'],
    bedrooms: 1,
    bathrooms: 1,
    floor: '2',
    totalFloors: 4,
    propertyAge: '2-3 years',
    furnished: 'Furnished',
    preferredTenant: 'Anyone',
    builtUpArea: 280,
    createdAt: '2025-02-25T09:15:00Z',
    updatedAt: '2025-02-25T09:15:00Z',
    reportedCount: 0,
    views: 456,
  },
];

export const getPropertiesByCity = (city: string): Property[] => {
  return properties.filter(p => p.city.toLowerCase() === city.toLowerCase() && p.status === 'live');
};

export const getPropertyById = (id: string): Property | undefined => {
  return properties.find(p => p.id === id);
};

export const getFilteredProperties = (filters: {
  city?: string;
  propertyType?: PropertyType;
  listingType?: ListingType;
  minPrice?: number;
  maxPrice?: number;
}): Property[] => {
  return properties.filter(p => {
    if (p.status !== 'live') return false;
    if (filters.city && p.city.toLowerCase() !== filters.city.toLowerCase()) return false;
    if (filters.propertyType && p.propertyType !== filters.propertyType) return false;
    if (filters.listingType && p.listingType !== filters.listingType) return false;
    if (filters.minPrice && p.price < filters.minPrice) return false;
    if (filters.maxPrice && p.price > filters.maxPrice) return false;
    return true;
  });
};
